spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:shell'
    username: panda
    password: 9779
  h2:
    console:
      enabled: true
  main:
    banner-mode: off
logging:
  level:
    root: error